[package]
name = "puga"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.51", features = ["derive"] }
urlencoding = "2.1.3"
uuid = {version = "1.18.1", features = ["v4", "v7"]}
